version: "2.1"
services:
  medusa:
    image: pymedusa/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=United States/Ohio
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./tv:/tv
    ports:
      - 80:8081
    restart: unless-stopped
